return {
  'uga-rosa/ccc.nvim',
  config = function()
    assert(vim.o.termguicolors == true)
    local ccc = require 'ccc'

    ccc.setup {
      -- Settings go here, bitch.
      highlighter = {
        auto_enable = true,
        lsp = true,
      },
      inputs = {
        ccc.input.rgb,
        ccc.input.hsl,
        ccc.input.hwb,
        ccc.input.lab,
        ccc.input.lch,
        ccc.input.oklab,
        ccc.input.oklch,
        ccc.input.cmyk,
        ccc.input.hsluv,
        ccc.input.okhsl,
        ccc.input.hsv,
        ccc.input.okhsv,
        ccc.input.xyz,
      },
      output = {
        ccc.output.hex,
        ccc.output.hex_short,
        ccc.output.css_rgb,
        ccc.output.css_rgba,
        ccc.output.css_hsl,
        ccc.output.css_hwb,
        ccc.output.css_lab,
        ccc.output.css_lch,
        ccc.output.css_oklab,
        ccc.output.css_oklch,
      },
      pickers = {
        -- ccc.picker.trailing_whitespace {
        --   ---@type table<string, string>
        --   --- Keys are filetypes, values are colors (6-digit hex)
        --   palette = {},
        --   ---@type string
        --   --- Default color. 6-digit hex representation.
        --   default_color = '#db7093',
        --   ---@type string[]|true
        --   --- List of filetypes for which highlighting is enabled or true.
        --   enable = true,
        --   ---@type string[]|fun(bufnr: number): boolean
        --   --- Used only when enable is true. List of filetypes to disable
        --   --- highlighting or a function that returns true when you want
        --   --- to disable it.
        --   disable = {},
        -- },
        ccc.picker.hex,
        ccc.picker.css_rgb,
        ccc.picker.css_hsl,
        ccc.picker.css_hwb,
        ccc.picker.css_lab,
        ccc.picker.css_lch,
        ccc.picker.css_oklab,
        ccc.picker.css_oklch,
        ccc.picker.custom_entries {
          -- your deep tints
          red = '#7d0000',
          green = '#007d00',
          blue = '#00007d',

          -- full CSS named-color set (normalized to 6-digit lowercase hex)
          aliceblue = '#f0f8ff',
          antiquewhite = '#faebd7',
          aqua = '#00ffff',
          aquamarine = '#7fffd4',
          azure = '#f0ffff',
          beige = '#f5f5dc',
          bisque = '#ffe4c4',
          black = '#000000',
          blanchedalmond = '#ffebcd',
          blue = '#0000ff',
          blueviolet = '#8a2be2',
          brown = '#a52a2a',
          burlywood = '#deb887',
          cadetblue = '#5f9ea0',
          chartreuse = '#7fff00',
          chocolate = '#d2691e',
          coral = '#ff7f50',
          cornflowerblue = '#6495ed',
          cornsilk = '#fff8dc',
          crimson = '#dc143c',
          cyan = '#00ffff',
          darkblue = '#00008b',
          darkcyan = '#008b8b',
          darkgoldenrod = '#b8860b',
          -- darkgray = '#a9a9a9',
          darkgreen = '#006400',
          darkgrey = '#a9a9a9',
          darkkhaki = '#bdb76b',
          darkmagenta = '#8b008b',
          darkolivegreen = '#556b2f',
          darkorange = '#ff8c00',
          darkorchid = '#9932cc',
          darkred = '#8b0000',
          darksalmon = '#e9967a',
          darkseagreen = '#8fbc8f',
          darkslateblue = '#483d8b',
          -- darkslategray = '#2f4f4f',
          darkslategrey = '#2f4f4f',
          darkturquoise = '#00ced1',
          darkviolet = '#9400d3',
          deeppink = '#ff1493',
          deepskyblue = '#00bfff',
          -- dimgray = '#696969',
          dimgrey = '#696969',
          dodgerblue = '#1e90ff',
          firebrick = '#b22222',
          floralwhite = '#fffaf0',
          forestgreen = '#228b22',
          fuchsia = '#ff00ff',
          gainsboro = '#dcdcdc',
          ghostwhite = '#f8f8ff',
          gold = '#ffd700',
          goldenrod = '#daa520',
          -- gray = '#808080',
          grey = '#808080',
          green = '#008000',
          greenyellow = '#adff2f',
          honeydew = '#f0fff0',
          hotpink = '#ff69b4',
          indianred = '#cd5c5c',
          indigo = '#4b0082',
          ivory = '#fffff0',
          khaki = '#f0e68c',
          lavender = '#e6e6fa',
          lavenderblush = '#fff0f5',
          lawngreen = '#7cfc00',
          lemonchiffon = '#fffacd',
          lightblue = '#add8e6',
          lightcoral = '#f08080',
          lightcyan = '#e0ffff',
          lightgoldenrodyellow = '#fafad2',
          -- lightgray = '#d3d3d3',
          lightgreen = '#90ee90',
          lightgrey = '#d3d3d3',
          lightpink = '#ffb6c1',
          lightsalmon = '#ffa07a',
          lightseagreen = '#20b2aa',
          lightskyblue = '#87cefa',
          -- lightslategray = '#778899',
          lightslategrey = '#778899',
          lightsteelblue = '#b0c4de',
          lightyellow = '#ffffe0',
          lime = '#00ff00',
          limegreen = '#32cd32',
          linen = '#faf0e6',
          magenta = '#ff00ff',
          maroon = '#800000',
          mediumaquamarine = '#66cdaa',
          mediumblue = '#0000cd',
          mediumorchid = '#ba55d3',
          mediumpurple = '#9370db',
          mediumseagreen = '#3cb371',
          mediumslateblue = '#7b68ee',
          mediumspringgreen = '#00fa9a',
          mediumturquoise = '#48d1cc',
          mediumvioletred = '#c71585',
          midnightblue = '#191970',
          mintcream = '#f5fffa',
          mistyrose = '#ffe4e1',
          moccasin = '#ffe4b5',
          navajowhite = '#ffdead',
          navy = '#000080',
          oldlace = '#fdf5e6',
          olive = '#808000',
          olivedrab = '#6b8e23',
          orange = '#ffa500',
          orangered = '#ff4500',
          orchid = '#da70d6',
          palegoldenrod = '#eee8aa',
          palegreen = '#98fb98',
          paleturquoise = '#afeeee',
          palevioletred = '#db7093',
          papayawhip = '#ffefd5',
          peachpuff = '#ffdab9',
          peru = '#cd853f',
          pink = '#ffc0cb',
          plum = '#dda0dd',
          powderblue = '#b0e0e6',
          purple = '#800080',
          rebeccapurple = '#663399',
          red = '#ff0000',
          rosybrown = '#bc8f8f',
          royalblue = '#4169e1',
          saddlebrown = '#8b4513',
          salmon = '#fa8072',
          sandybrown = '#f4a460',
          seagreen = '#2e8b57',
          seashell = '#fff5ee',
          sienna = '#a0522d',
          silver = '#c0c0c0',
          skyblue = '#87ceeb',
          slateblue = '#6a5acd',
          -- slategray = '#708090',
          slategrey = '#708090',
          snow = '#fffafa',
          springgreen = '#00ff7f',
          steelblue = '#4682b4',
          tan = '#d2b48c',
          teal = '#008080',
          thistle = '#d8bfd8',
          tomato = '#ff6347',
          turquoise = '#40e0d0',
          violet = '#ee82ee',
          wheat = '#f5deb3',
          white = '#ffffff',
          whitesmoke = '#f5f5f5',
          yellow = '#ffff00',
          yellowgreen = '#9acd32',
          -- expansion 1
          ['acid green'] = '#8ffe09',
          adobe = '#bd6c48',
          algae = '#54ac68',
          ['algae green'] = '#21c36f',
          ['almost black'] = '#070d0d',
          amber = '#feb308',
          amethyst = '#9b5fc0',
          ['apple green'] = '#76cd26',
          apple = '#6ecb3c',
          apricot = '#ffb16d',
          aqua = '#13eac9', -- xkcd aqua (distinct from CSS aqua/cyan)
          ['aqua blue'] = '#02d8e9',
          ['aqua green'] = '#12e193',
          aquamarine = '#2ee8bb', -- xkcd variant (CSS already present above)
          ['army green'] = '#4b5d16',
          asparagus = '#77ab56',
          aubergine = '#3d0734',
          auburn = '#9a3001',
          avocado = '#90b134',
          ['avocado green'] = '#87a922',
          azul = '#1d5dec',
          azure = '#069af3', -- xkcd azure (CSS 'azure' is different; you might keep both)
          ['baby blue'] = '#a2cffe',
          ['baby green'] = '#8cff9e',
          ['baby pink'] = '#ffb7ce',
          ['baby poo'] = '#ab9004',
          ['banana yellow'] = '#fafe4b',
          banana = '#ffff7e',
          ['barbie pink'] = '#da1884',
          ['barn red'] = '#7c0a02',
          basil = '#32612d',
          beigegreen = '#c9d179',
          bermuda = '#62c9c3',
          bisque2 = '#eed5b7',
          ['bitter green'] = '#86a17d',
          blackish = '#181a1b',
          ['bland'] = '#afa88b',
          ['blood orange'] = '#fe4b03',
          blood = '#770001',
          ['blood red'] = '#980002',
          bluegreen = '#137e6d',
          bluegrey = '#6f8fae',
          ['blue purple'] = '#5729ce',
          ['blue violet'] = '#5d06e9',
          ['blurple'] = '#5539cc',
          blush = '#f29e8e',
          ['blush pink'] = '#fe828c',
          ['booger green'] = '#96b403',
          brass = '#b5a642',
          ['bright aqua'] = '#0bf9ea',
          ['bright blue'] = '#0165fc',
          ['bright cyan'] = '#41fdfe',
          ['bright fuchsia'] = '#fe46a5',
          ['bright green'] = '#01ff07',
          ['bright lavender'] = '#c760ff',
          ['bright lilac'] = '#c95efb',
          ['bright lime'] = '#87fd05',
          ['bright magenta'] = '#ff08e8',
          ['bright mint'] = '#4ffcf1',
          ['bright orange'] = '#ff5b00',
          ['bright pink'] = '#fe01b1',
          ['bright purple'] = '#be03fd',
          ['bright red'] = '#ff000d',
          ['bright sky blue'] = '#02ccfe',
          ['bright teal'] = '#01f9c6',
          ['bright turquoise'] = '#08e8de',
          ['bright violet'] = '#ad0afd',
          ['bright yellow'] = '#fffd01',
          bronze = '#a87900',
          brownish = '#9c6d57',
          ['brownish green'] = '#6a6e09',
          ['brownish grey'] = '#86775f',
          ['brownish orange'] = '#cb7723',
          ['brownish pink'] = '#c27e79',
          ['brownish purple'] = '#76424e',
          ['brownish red'] = '#9e3623',
          ['bubble gum'] = '#ff69af',
          ['bubblegum pink'] = '#fe83cc',
          buff = '#f0dc82',
          burgundy = '#610023',
          burlap = '#a1815b',
          ['burnt orange'] = '#c04e01',
          ['burnt red'] = '#9f2305',
          ['burnt siena'] = '#b75203',
          ['butter yellow'] = '#fffd74',
          butter = '#ffff81',
          buttermilk = '#fff1b5',
          cadet = '#536872',
          camo = '#7f8f4e',
          ['camo green'] = '#526525',
          canary = '#fdff63',
          caramel = '#af6f09',
          carmine = '#960018',
          carnation = '#fd798f',
          celadon = '#befdb7',
          celeste = '#b2ffff',
          cement = '#a5a391',
          champagne = '#f7e7ce',
          charcoal = '#343837',
          chartreuse2 = '#c1f80a',
          cherry = '#cf0234',
          ['cherry red'] = '#f7022a',
          chestnut = '#742802',
          ['chocolate brown'] = '#411900',
          cinnamon = '#ac4f06',
          claret = '#680018',
          cobalt = '#0047ab',
          coffee = '#6f4e37',
          copper = '#b66325',
          coral2 = '#fc5a50',
          corn = '#fbec5d',
          ['cornflower'] = '#93ccea',
          cranberry = '#9e003a',
          cream = '#fffdd0',
          ['creamy yellow'] = '#fffdb8',
          crimson2 = '#d01c1f',
          curry = '#caa510',
          cyanide = '#00ffff', -- alias for clarity; different sources call it cyanide/acid cyan
          daffodil = '#ffff31',
          dandelion = '#fedf08',
          denim = '#3b5b92',
          desert = '#ccad60',
          ['desert sand'] = '#edc9af',
          dijon = '#c29200',
          dusk = '#4e5481',
          ['dusty blue'] = '#5a86ad',
          ['dusty green'] = '#76a973',
          ['dusty pink'] = '#d58a94',
          ['dusty purple'] = '#825f87',
          eggplant = '#380835',
          eggshell = '#fffcc4',
          ['electric blue'] = '#0652ff',
          emerald = '#01a049',
          ['fern green'] = '#548d44',
          fawn = '#e5aa70',
          fuchsia2 = '#ed0dd9',
          ['golden brown'] = '#996515',
          ['golden yellow'] = '#fec615',
          goldleaf = '#b8860b',
          grape = '#6c3461',
          grass = '#5cac2d',
          ['grass green'] = '#3f9b0b',
          graphite = '#3b3b3b',
          -- ['gray blue'] = '#6b8ba4',
          -- ['gray green'] = '#8d9b90',
          ['greige'] = '#b7ad9b',
          ['green blue'] = '#06b48b',
          ['green grey'] = '#778c7a',
          ['green teal'] = '#0cb577',
          ['green yellow'] = '#b5ce08',
          gunmetal = '#2a3439',
          heather = '#a484ac',
          hibiscus = '#b6316c',
          honey = '#febf14',
          iceberg = '#daedf3',
          indigo2 = '#3a18b1',
          ['iris'] = '#5d3fd3',
          ivory2 = '#fffff4',
          jade = '#00a86b',
          jasmine = '#f8de7e',
          khaki2 = '#b7aa5d',
          lapis = '#1c2c5b',
          lavender2 = '#c79fef',
          ['leaf green'] = '#5ca904',
          leather = '#ac7434',
          lemon = '#fdff52',
          ['lemon green'] = '#adf802',
          ['lemon yellow'] = '#fdff38',
          lilac = '#cea2fd',
          lime2 = '#aaff32',
          ['lime green'] = '#89fe05',
          linen2 = '#faf0e6',
          magenta2 = '#ff0097',
          mahogany = '#4a0100',
          maize = '#f2c649',
          ['marine blue'] = '#01386a',
          marigold = '#fcc006',
          mauve = '#ae7181',
          melon = '#ff7855',
          ['midnight'] = '#03012d',
          ['midnight purple'] = '#280137',
          ['midnight blue 2'] = '#020035',
          ['military green'] = '#667c3e',
          mint = '#3eb489',
          ['mint green'] = '#9ffeb0',
          ['moss green'] = '#658b38',
          mud = '#735c12',
          ['mud brown'] = '#60460f',
          ['mustard'] = '#ceb301',
          ['mustard yellow'] = '#d2bd0a',
          ['navy blue 2'] = '#001146',
          neonblue = '#04d9ff',
          neongreen = '#0cff0c',
          ['neon pink'] = '#fe019a',
          ['neon purple'] = '#bc13fe',
          ochre = '#bf9005',
          olive2 = '#6e750e',
          ['olive drab 2'] = '#6f7632',
          ['olive green 2'] = '#677a04',
          opal = '#a8c3bc',
          orchid2 = '#b565a7',
          ['pale blue'] = '#d0fefe',
          ['pale brown'] = '#b1916e',
          ['pale green'] = '#c7fdb5',
          ['pale grey'] = '#fdfdfe',
          ['pale lime'] = '#befd73',
          ['pale orange'] = '#ffa756',
          ['pale pink'] = '#ffcfdc',
          ['pale purple'] = '#b790d4',
          ['pale red'] = '#d9544d',
          ['pale teal'] = '#82cbb2',
          papaya = '#ff9700',
          paprika = '#8d3f2d',
          peach = '#ffb07c',
          ['peach pink'] = '#ff9a8a',
          pear = '#c9cc3f',
          periwinkle2 = '#8e82fe',
          petroleum = '#013a4a',
          pewter = '#99aabb',
          ['pine green'] = '#0a481e',
          pinkish = '#d46a7e',
          ['pinkish red'] = '#f10c45',
          pistachio = '#c0fa8b',
          ['plum 2'] = '#701c4d',
          ['powder blue 2'] = '#b1d1fc',
          ['pumpkin'] = '#e17701',
          ['pumpkin orange'] = '#fb7d07',
          puce = '#a57e52',
          ['puce pink'] = '#dd85d7',
          ['pure blue'] = '#0203e2',
          ['purple blue'] = '#5d21d0',
          ['purple brown'] = '#673a3f',
          ['purple grey'] = '#866f85',
          ['purple pink'] = '#e03fd8',
          ['purple red'] = '#990147',
          ['racing green'] = '#014600',
          raspberry = '#b00149',
          ['raw sienna'] = '#d27d46',
          ['real teal'] = '#005f5e',
          ['reddish'] = '#c44240',
          ['reddish brown'] = '#7f2b0a',
          ['reddish grey'] = '#997570',
          ['reddish orange'] = '#f8481c',
          ['reddish pink'] = '#fe2c54',
          ['red orange'] = '#fd3c06',
          ['red purple'] = '#820747',
          ['rich blue'] = '#021bf9',
          robinsegg = '#98eff9',
          ['robin egg blue'] = '#8af1fe',
          rose2 = '#cf6275',
          rosemary = '#4b7f52',
          ['royal purple'] = '#4b006e',
          rubine = '#d10056',
          saffron = '#f4c430',
          sage = '#87ae73',
          salmon2 = '#ff796c',
          sand = '#e2ca76',
          sandstone = '#c9ae74',
          sangria = '#5f1914',
          sapphire = '#0f52ba',
          scarlet = '#ff2400',
          seablue = '#047495',
          seaglass = '#7bc8a4',
          sepia = '#704214',
          shamrock = '#01b44c',
          ['shocking pink'] = '#fe02a2',
          sienna2 = '#a0522d',
          sky = '#82cafc',
          slate = '#516572',
          smalt = '#003399',
          smoke = '#738276',
          ['soft blue'] = '#6488ea',
          ['soft green'] = '#6fc276',
          ['soft pink'] = '#fdb0c0',
          ['soft purple'] = '#a66fb5',
          spruce = '#0a5f38',
          steel = '#738595',
          straw = '#e4d96f',
          ['sunflower'] = '#ffc512',
          ['sunflower yellow'] = '#ffda03',
          ['sunset orange'] = '#fe4c40',
          ['tangerine'] = '#f28500',
          taupe = '#b9a281',
          tea = '#65ab7c',
          teal2 = '#029386',
          terracotta = '#ca6641',
          thistle2 = '#d8bfd8',
          toffee = '#b05f03',
          tomato2 = '#ef4026',
          topaz = '#13bbaf',
          turquoise2 = '#06c2ac',
          ultramarine = '#2000b1',
          umber = '#635147',
          vanilla = '#f3e5ab',
          vermilion = '#e34234',
          ['very light blue'] = '#d5ffff',
          ['very light green'] = '#aaffd4',
          ['very light pink'] = '#fff4f2',
          ['very light purple'] = '#f6cefc',
          violet2 = '#ad0afd',
          viridian = '#40826d',
          ['vomit green'] = '#89a203',
          ['watermelon'] = '#fd4659',
          wheat2 = '#f5deb3',
          wine = '#80013f',
          ['wine red'] = '#7b0323',
          wisteria = '#c9a0dc',
          yolk = '#fffd01',
          ['zucchini'] = '#17462e',
        },
      },
    }
    local map = vim.keymap.set
    map(
      {
        'n',
      },
      '<leader>cp',
      '<CMD>CccPick<CR>',
      {
        desc = '(hover enabled) Open Color Picker.',
      }
    )
  end,
}
